{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}-gateway
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
